repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.3.2
    hooks:
      - id: ansible-lint

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: tflint
      - id: terragrunt-hclfmt
      - id: shellcheck

  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform fmt
        description: Reformat configuration in the standard style
        entry: .hooks/terraform-fmt.sh
        language: script
        files: (\.tf|\.tfvars)$
        exclude: >
          (?x)^(
            .+\.terraform/\.*$
          )$
        require_serial: true
