# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "1.1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  profile  = "rfc4251"
  region   = "eu-central-1"
  insecure = false
  default_tags {
    tags = {
      Terraform = "true"
    }
  }
}
