name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: terraform-linters/setup-tflint@v3.0.0
      - uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.21.13
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
