name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3
